"""init

Revision ID: d273f570e4f2
Revises: f0d313ecc9bc
Create Date: 2022-04-12 18:28:53.422562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd273f570e4f2'
down_revision = 'f0d313ecc9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'state1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('state1', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
